### ISSUE TITLE
Can't disable sessionIdUrlRewriting

### ISSUE THREAD

**Issue by richmidwinter** [silb/dropwizard-shiro#11]
I couldn't stop shiro putting the JSESSIONID value into the URL. There's a simple line of config to correct this behaviour:

  sessionManager.sessionIdUrlRewritingEnabled = false

But it doesn't work unless you update the version of shiro. See https://github.com/silb/dropwizard-shiro/pull/10

**Comment by silb** [comment]
You can simply update the version in the direct dependency to Shiro from your project.
