### ISSUE TITLE
Dropwizard authentication with Shiro authorization

### ISSUE THREAD

**Issue by dllx** [silb/dropwizard-shiro#12]
Can the authorization part from Shiro be used with authentication provided by Dropwizard?
We're using OAuth2 authentication coming with Dropwizard, but would like to use the permissions-based authorization from Shiro. What would be needed to do this? Would we need to wrap a Shiro Subject around the User/Principal provided by Dropwizard?

**Comment by silb** [comment]
It is meant as a replacement for Dropwizard Authentication.

**Comment by dllx** [comment]
I think we have managed to use it as authorization only by using an Authenticator wrapper that wraps the our existing OAuth2Authenticator and then does a login on the Shiro subject.

The realm does not check any credentials for the login (the user is already authenticated) and uses the user object from the OAuth2Authenticator as principal.

Then, for authorization checks, it can be used at will.
