### ISSUE TITLE
Dropwizard 0.8 Support

### ISSUE THREAD

**Issue by ykim** [silb/dropwizard-shiro#5]
I was wondering when dropwizard 0.8 support would be available. It would be really awesome to use this library in conjunction with Jersey 2! :)

**Comment by mlamina** [comment]
+1 for DW 0.8! This library is more or less the reason why I haven't updated yet. If possible, I'd be glad to help :)

**Comment by silb** [comment]
See <https://github.com/silb/shiro-jersey/issues/6>. The DropWizard 0.8.0 support is pretty much complete, I just need to merge and release it.

**Comment by silb** [comment]
Version 0.2.0 has been released with support for Dropwizard 0.8.0.
