### ISSUE TITLE
Support for DW 1.0

### ISSUE THREAD

**Issue by extensia** [silb/dropwizard-shiro#9]
First, thanks for creating dropwizard-shiro. A very appreciated contribution to the community!

Do you know if the current version works with DW 1.0? I plan on doing some testing and did not know whether the current version is compatible or if a new release is planned.

Best Regards,
David

**Comment by silb** [comment]
I have run the integration tests against Dropwizard 1.0.0. They all pass, so the current version 0.2.0 is compatible with Dropwizard 1.0.
